[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
adapter_swap = "3wQCqUNGMBZL3Pe1v1iyqvonKMNMHjgByEw7iBTGHwyN"
tribe_vault = "ESRKS2xBKnuTZWU7qQip2koV7uG742ehB4qbojwtTrZs"
test_adapter = "E88wFPQJPYv7PoeV2JbwEw76u6oiRS4m2fZSqqhaG2JA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/execute.ts"
